In [1]:
import pandas as pd
df=pd.read_csv('bank_loan_risk_dataset.csv')
df

,loan_id,customer_id,age,employment_type,credit_score,annual_income,loan_amount,loan_status,term,years_in_current_job,home_ownership,purpose,monthly_debt,years_of_credit_history,number_of_open_accounts,number_of_credit_problems,current_credit_balance,maximum_open_credit,bankruptcies,tax_liens
0,L0001,C0001,59,Unemployed,415,448683,830722,Approved,Short Term,16,Own Home,Debt Consolidation,44287,23.4,1,3,299768,493316,0,0
1,L0002,C0002,49,Salaried,490,1483253,1436465,Approved,Long Term,4,Own Home,Home Improvement,15380,8.7,13,1,16823,422013,1,0
2,L0003,C0003,35,Salaried,552,226790,526467,Approved,Long Term,15,Rent,Education,28984,19.7,3,2,28489,975683,0,0
3,L0004,C0004,63,Business,460,1891738,406600,Rejected,Long Term,5,Rent,Home Improvement,46633,18.3,8,1,181033,360925,1,2
4,L0005,C0005,28,Self-Employed,555,1011721,1414133,Approved,Short Term,7,Mortgage,Education,10125,12.6,3,4,301262,236339,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,L0196,C0196,22,Salaried,431,963185,332272,Rejected,Long Term,9,Mortgage,Education,19625,29.7,5,4,65077,761404,1,1
196,L0197,C0197,22,Business,369,517537,435925,Rejected,Long Term,10,Own Home,Debt Consolidation,35893,13.9,10,3,122782,768675,1,1
197,L0198,C0198,48,Business,551,1977489,816641,Rejected,Long Term,6,Rent,Debt Consolidation,12793,2.4,4,3,112932,932487,0,1
198,L0199,C0199,43,Unemployed,714,862301,764743,Approved,Short Term,17,Own Home,Business Loan,33007,2.1,13,2,475122,252416,0,1
199,L0200,C0200,57,Salaried,744,750222,639833,Rejected,Long Term,3,Rent,Medical,27766,22.6,4,4,412744,974300,1,0

Q1 Average loan amount by employment type

In [2]:
a=df.groupby('employment_type')['loan_amount'].mean()
a

employment_type
Business         800146.311111
Salaried         824903.729167
Self-Employed    711128.200000
Unemployed       756155.507463
Name: loan_amount, dtype: float64

Q2.Default rate by employment type

In [3]:
df['is_default'] = df['loan_status'] == 'Default'
a2=df.groupby('employment_type')['is_default'].mean()*100
a2

employment_type
Business         11.111111
Salaried          8.333333
Self-Employed     5.000000
Unemployed        8.955224
Name: is_default, dtype: float64

Q3.Customer have below 500 credit score

In [4]:
a3=df[df['credit_score']<500]
a3

,loan_id,customer_id,age,employment_type,credit_score,annual_income,loan_amount,loan_status,term,years_in_current_job,...,purpose,monthly_debt,years_of_credit_history,number_of_open_accounts,number_of_credit_problems,current_credit_balance,maximum_open_credit,bankruptcies,tax_liens,is_default
0,L0001,C0001,59,Unemployed,415,448683,830722,Approved,Short Term,16,...,Debt Consolidation,44287,23.4,1,3,299768,493316,0,0,False
1,L0002,C0002,49,Salaried,490,1483253,1436465,Approved,Long Term,4,...,Home Improvement,15380,8.7,13,1,16823,422013,1,0,False
3,L0004,C0004,63,Business,460,1891738,406600,Rejected,Long Term,5,...,Home Improvement,46633,18.3,8,1,181033,360925,1,2,False
6,L0007,C0007,59,Salaried,427,949074,1403038,Approved,Short Term,11,...,Business Loan,6033,11.0,1,4,91816,467168,1,1,False
7,L0008,C0008,39,Unemployed,317,1736038,300875,Approved,Long Term,14,...,Business Loan,39873,18.9,5,1,163335,890230,0,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,L0182,C0182,62,Unemployed,493,1171375,1279024,Approved,Short Term,15,...,Medical,9421,3.2,1,2,114648,614871,1,2,False
183,L0184,C0184,44,Salaried,328,739542,285659,Approved,Long Term,12,...,Debt Consolidation,35537,28.0,14,3,38795,921803,1,0,False
184,L0185,C0185,35,Self-Employed,464,1292814,439678,Rejected,Short Term,10,...,Home Improvement,19727,8.3,9,3,196368,734393,1,2,False
195,L0196,C0196,22,Salaried,431,963185,332272,Rejected,Long Term,9,...,Education,19625,29.7,5,4,65077,761404,1,1,False
196,L0197,C0197,22,Business,369,517537,435925,Rejected,Long Term,10,...,Debt Consolidation,35893,13.9,10,3,122782,768675,1,1,False

Q4.Age group have highest loan amount

In [12]:
df.groupby('age')['loan_amount'].sum().sort_values(ascending=False).head(1)

age
59    9457736
Name: loan_amount, dtype: int64

Q5.Average income of approved loan customer

In [6]:
# a5=df[df['loan_status']=='Approved']
# a5['annual_income'].mean()
df[df['loan_status']=='Approved']['annual_income'].mean()

np.float64(1058359.3553719008)

Q6.Count loan application by loan status

In [7]:
df.groupby('loan_status')['loan_status'].count()
# a6=df['loan_status'].value_counts()
# a6

loan_status
Approved    121
Default      17
Rejected     62
Name: loan_status, dtype: int64

Q7.Customer having loan amount greater than income

In [8]:
df[df['loan_amount']>df['annual_income']]

,loan_id,customer_id,age,employment_type,credit_score,annual_income,loan_amount,loan_status,term,years_in_current_job,...,purpose,monthly_debt,years_of_credit_history,number_of_open_accounts,number_of_credit_problems,current_credit_balance,maximum_open_credit,bankruptcies,tax_liens,is_default
0,L0001,C0001,59,Unemployed,415,448683,830722,Approved,Short Term,16,...,Debt Consolidation,44287,23.4,1,3,299768,493316,0,0,False
2,L0003,C0003,35,Salaried,552,226790,526467,Approved,Long Term,15,...,Education,28984,19.7,3,2,28489,975683,0,0,False
4,L0005,C0005,28,Self-Employed,555,1011721,1414133,Approved,Short Term,7,...,Education,10125,12.6,3,4,301262,236339,0,2,False
5,L0006,C0006,41,Self-Employed,622,648345,1024304,Approved,Short Term,17,...,Education,38059,11.6,8,4,110417,525595,1,0,False
6,L0007,C0007,59,Salaried,427,949074,1403038,Approved,Short Term,11,...,Business Loan,6033,11.0,1,4,91816,467168,1,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,L0186,C0186,52,Salaried,721,201252,904016,Rejected,Short Term,12,...,Business Loan,48882,23.7,2,2,31447,467216,1,1,False
186,L0187,C0187,52,Self-Employed,638,1026196,1203113,Default,Short Term,9,...,Home Improvement,6358,24.9,5,1,177670,161032,0,0,True
189,L0190,C0190,32,Salaried,641,515826,838260,Default,Long Term,6,...,Debt Consolidation,25164,14.1,11,0,266190,511552,1,1,True
192,L0193,C0193,23,Salaried,626,527359,836275,Approved,Short Term,12,...,Education,46311,14.1,6,1,239817,123869,1,1,False
194,L0195,C0195,37,Self-Employed,600,206949,621650,Approved,Long Term,9,...,Debt Consolidation,40467,4.1,3,3,335422,919807,1,2,False

Q8. Top 10 highest loan amount

In [9]:
df.sort_values('loan_amount',ascending=False).head(10)

,loan_id,customer_id,age,employment_type,credit_score,annual_income,loan_amount,loan_status,term,years_in_current_job,...,purpose,monthly_debt,years_of_credit_history,number_of_open_accounts,number_of_credit_problems,current_credit_balance,maximum_open_credit,bankruptcies,tax_liens,is_default
108,L0109,C0109,28,Unemployed,696,678007,1498021,Approved,Long Term,9,...,Medical,33010,9.1,7,3,165289,671424,0,0,False
114,L0115,C0115,57,Salaried,389,725303,1497960,Approved,Short Term,5,...,Home Improvement,36905,12.2,9,0,107756,472381,0,0,False
67,L0068,C0068,54,Self-Employed,546,1259599,1479551,Approved,Long Term,11,...,Home Improvement,33348,17.7,2,0,206103,888574,1,1,False
102,L0103,C0103,62,Unemployed,726,773695,1471796,Approved,Short Term,3,...,Business Loan,30211,3.3,14,3,411220,167886,1,2,False
113,L0114,C0114,44,Self-Employed,334,1417540,1470499,Rejected,Short Term,2,...,Medical,25171,11.6,11,3,218347,377231,1,0,False
56,L0057,C0057,56,Business,426,701108,1469184,Default,Long Term,1,...,Education,13207,10.9,8,0,75794,519164,0,1,True
193,L0194,C0194,57,Salaried,516,1851451,1466012,Approved,Short Term,18,...,Business Loan,31371,26.6,8,3,360104,841842,0,2,False
85,L0086,C0086,35,Salaried,656,991267,1465833,Approved,Short Term,14,...,Education,26596,17.6,14,1,377631,192312,0,1,False
51,L0052,C0052,64,Unemployed,419,1058158,1465400,Approved,Short Term,9,...,Education,33010,15.7,10,3,90257,289017,1,0,False
40,L0041,C0041,59,Unemployed,743,1734837,1462290,Approved,Long Term,7,...,Home Improvement,39574,29.3,4,3,424600,728743,1,1,False

Q9. Average credit by loan status

In [10]:
df.groupby('loan_status')['credit_score'].mean()

loan_status
Approved    555.223140
Default     591.176471
Rejected    572.032258
Name: credit_score, dtype: float64

Q10.Employment type with highest loan approval

In [11]:
df[df['loan_status'] == 'Approved']['employment_type'].value_counts().idxmax()

'Unemployed'